services:
  database:
    image: mysql
    container_name: crm-database
    ports:
      - "3309:3306"
    restart: always
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: faride
      MYSQL_PASSWORD: faride1234
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - crm

  phpmyadmin:
    image: phpmyadmin
    container_name: crm-phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    networks:
      - crm
  redis:
    image: redis:alpine
    container_name: crm-redis
    restart: always
    ports:
      - "6381:6379"
    networks:
      - crm


volumes:
  dbdata:

networks:
  crm:
